### PR TITLE
Sync up the variable naming for demuxed audio so it correctly carries…

### PR DESCRIPTION
**Pull request by craigmc-ottera**
… through from server init to session

The param as it was set never got through from channel engine initialization to actual channel start

### CODE REVIEW

**Review by birme — APPROVED** [review]
Good catch! Looks good.

Thinking of perhaps having this as part of the streamerOpts, e.g. this.streamerOpts.useDemuxedAudio in the Channel Engine class but this fix will do for now.

**Comment by birme** [comment]
Merged the fix. Do you need a new build created instantly?

**Comment by craigmc-ottera** [comment]
I wonder if it would be practical to enable the audio demux on a per-channel basis, vs just at the engine level, or if that just meets our specific use-case. It seems to me like the session store would all still work properly, and so I don't see a real reason not to be able to have it be per channel and not just a top level option.... thoughts?

**Comment by birme** [comment]
I agree, having it on a per-channel basis would be beneficial.

**Pull request merged**
